{% set name = "leafmaptools" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 567668ea841d065657b7ea50eea34a2d10c2417d2c86d228209615bbb6c1e78b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    
    - geojson
    - h3
    - ipyfilechooser
    - ipyleaflet
    - ipywidgets
    - mercantile
    - python >=3.6

test:
  imports:
    - leafmaptools

about:
  home: "https://github.com/giswqs/leafmaptools"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for building a tool widgets infrastructure with ipyleaflet and ipywidgets"
  doc_url: https://leafmaptools.gishub.org
  dev_url: https://github.com/giswqs/leafmaptools

extra:
  recipe-maintainers:
    - giswqs
    - deeplook
